spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB
  mvc:
    async:
      request-timeout: 50000
  profiles:
    active: local
  jpa:
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    generate-ddl: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mysql://13.124.1.36:3306/tybms?allowPublicKeyRetrieval=true&useSSL=false
      minimum-idle: 3
      maximum-pool-size: 10
      connection-timeout: 3000
      max-lifetime: 58000
      idle-timeout: 30000
      auto-commit: false
    username: dundung
    password: dundung
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
